[package]
name = "giulio"
version = "0.0.0"
edition = "2021"
license = "BSD-2-Clause"
authors = ["Thibault Vincent <th1bault.vincent@proton.me>"]

[dependencies]
lazy_static = "1.5.0"
rand = "0.8.5"
termcolor = "1.4.1"
